pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.12.0-alpine3.18'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') { 
            agent any
            environment { 
                VOLUME = '/mnt/c/path/to/workspace/Python-Pipeline/sources:/src' // Cambia esta ruta
                IMAGE = 'cdrx/pyinstaller-linux:python2'
            }
            steps {
                dir(path: env.BUILD_ID) { 
                    unstash(name: 'compiled-results') 
                    // Paso de depuración para listar archivos en /src
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} ls /src"
                    // Ejecutar PyInstaller
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} pyinstaller -F /src/add2vals.py"
                }
            }
            post {
                success {
                    archiveArtifacts "sources/dist/add2vals" 
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} rm -rf build dist"
                }
            }
        }
    }
}
