pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.12.0-alpine3.18'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') { 
            agent any
            environment { 
                VOLUME = 'D:/Escritorio/UCA/2025/VS/PRACTICAS/ENTREGABLE3/PARTE1/simple-python-pyinstaller-app/sources:/src'
                IMAGE = 'cdrx/pyinstaller-linux:python2'
            }
            steps {
                dir('workspace') {
                    unstash(name: 'compiled-results') 
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F add2vals.py'"
                    sh "mkdir -p ${WORKSPACE}/dist"
                    sh "cp /src/dist/add2vals ${WORKSPACE}/dist/"
                }
            }
            post {
                success {
                    archiveArtifacts artifacts :'dist/add2vals' 
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} 'rm -rf /src/build /src/dist'"                }
            }
        }
    }
}
