FROM python:3.12-slim

# Instala dependencias necesarias para PyInstaller
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    && pip install --no-cache-dir pyinstaller \
    && apt-get clean

# Establece el directorio de trabajo
WORKDIR /workspace

# Default CMD
CMD ["bash"]
